### ISSUE TITLE
PM-VINIL-001: Falta botón de crear nuevo álbum

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#84]
En la barra de título de la aplicación no se observa el botón o funcionalidad que permita la creación de un nuevo álbum, cómo se definió en los wireframe navegables.

Enlace wireframe navegables:
https://www.figma.com/proto/0X6lzMYUNkZtcTQa8qLi0d/Vinilos-Mobile?node-id=9%3A3&scaling=scale-down&page-id=0%3A1&starting-point-node-id=9%3A3

Evidencia de la prueba:
https://youtu.be/MfkP_ieWF7k

**Comment by hvaron83** [comment]
Esta funcionalidad no se contempla dado que no hace parte de las historias de usuario a implementar en este Sprint.
