### ISSUE TITLE
PM-VINIL-002: No sale el mensaje “No tienes álbumes en el catálogo”

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#85]
En el espacio principal de la aplicación no se muestra un mensaje que indique al usuario que no tiene álbumes registrados en el catálogo.

Evidencia de la prueba:
https://youtu.be/oe6PPgIrkUQ

**Comment by hvaron83** [comment]
Se verifica el hallazgo reportado para ser corregido en el siguiente sprint.

**Comment by jhinariv** [comment]
El escenario no se replicable para un usuario normal que esté navegando por la aplicación.
