### ISSUE TITLE
PM-VINIL-004: falta mensaje informativo cuando el API REST está caído

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#86]
En el espacio principal de la aplicación no se muestra un mensaje que indique al usuario que el API REST no se encuentra operativo.  Se sugiere incluir el mensaje “No es posible consultar el catálogo de álbumes en este momento.  Por favor consulte con el administrador del sistema.”.

Evidencia de la prueba:
https://youtu.be/bCq2fBX2TKc

**Comment by hvaron83** [comment]
Se verifica el hallazgo reportado para ser corregido en el siguiente sprint.
