### ISSUE TITLE
PM-VINIL-005: falta mensaje informativo cuando el dispositivo no tiene acceso a Internet

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#87]
En el espacio principal de la aplicación no se muestra un mensaje que indique al usuario que el dispositivo no tiene acceso a Internet. Se sugiere incluir el mensaje "No es posible consultar el catálogo de álbumes en este momento.  Compruebe su conexión a Internet.".

Evidencia de la prueba:
https://youtu.be/N90lxyfcyt4

**Comment by hvaron83** [comment]
Se verifica el hallazgo reportado para ser corregido en el siguiente sprint.
