### ISSUE TITLE
PM-VINIL-006: Elemento no funcional

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#88]
Aparece un elemento visual de tipo vínculo para retornar al catálogo de álbumes que no es funcional.  Se sugiere eliminarlo.

Evidencia de la prueba:
https://youtu.be/uh6yiiX23sk

**Comment by hvaron83** [comment]
Se retira el elemento tipo vínculo de retorno al catálogo de álbumes de acuerdo a lo especificado.
