### ISSUE TITLE
PM-VINIL-006: elementos faltantes

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#89]
- No se muestra información de Artistas del álbum y Lista de tracks asociados al álbum (título del Track y duración)"
- No aparece un elemento de texto tipo vínculo con el texto “Asociar Track a Álbum”

Evidencia de la prueba:
https://youtu.be/uh6yiiX23sk

**Comment by jhinariv** [comment]
El escenario no se replicable para un usuario normal que esté navegando por la aplicación.
