### ISSUE TITLE
PM-VINIL-007: comportamiento anormal al consultar álbum con ID no existente

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#90]
- El ID del album se cambia a uno no existente (ID = 300) por código fuente y aún así presenta la información de dicho ID
- No aparece el mensaje “No es posible consultar el detalle del álbum seleccionado en este momento."

Evidencia de la prueba:
https://youtu.be/BJHxJKPuKIw

**Comment by hvaron83** [comment]
Prueba no valida, el tipo de prueba no es replicable por un usuario final.
