### ISSUE TITLE
PM-VINIL-009: comportamiento anormal al consultar detalle de álbum con API REST caído

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#91]
- No aparece el mensaje “No es posible consultar el detalle del álbum seleccionado en este momento.  Por favor consulte con el administrador del sistema.”
- Se presenta la información detallada del álbum al seleccionar la opción desde el catálogo del álbum, a pesar que el API REST no responde

Evidencia de la prueba:
https://youtu.be/icBRXdNhm2s

**Comment by hvaron83** [comment]
Prueba no valida, el tipo de prueba no es replicable por un usuario final.
