### ISSUE TITLE
PM-VINIL-010: comportamiento anormal al consultar detalle de álbum con dispositivo sin Internet

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#92]
- No aparece el mensaje “No es posible consultar el detalle del álbum seleccionado en este momento.  Compruebe su conexión a Internet.”
- Se presenta la información detallada del álbum al seleccionar la opción desde el catálogo del álbum, a pesar que el dispositivo no tiene la conexión a Internet en el momento

Evidencia de la prueba:
https://youtu.be/hf_3NUZcvR8

**Comment by hvaron83** [comment]
Prueba no valida, el tipo de prueba no es replicable por un usuario final.
