### ISSUE TITLE
PM-VINIL-011: No sale el mensaje "El álbum no tiene artistas asociados"

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#93]
En el espacio de detalle de álbum de la aplicación no se muestra un mensaje que indique al usuario que el álbum no tiene artistas asociados.

Evidencia de la prueba:
https://youtu.be/xBP4k6qNOQU

**Comment by jhinariv** [comment]
El escenario no se replicable para un usuario normal que esté navegando por la aplicación.
