### ISSUE TITLE
PM-VINIL-012: - No aparece el texto “El álbum no tiene tracks asociados”

### ISSUE THREAD

**Issue by cjrojasj1** [hvaron83/MISW-4203-Moviles-EquipoDinamita#94]
En el espacio de detalle de álbum de la aplicación no se muestra un mensaje que indique al usuario que el álbum no tiene tracks asociados.

Evidencia de la prueba:
https://youtu.be/AbyRVsqmnc4

**Comment by jhinariv** [comment]
El escenario no se replicable para un usuario normal que esté navegando por la aplicación.
